//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_Muzey.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exsponati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exsponati()
        {
            this.Posetiteli = new HashSet<Posetiteli>();
            this.Sklad = new HashSet<Sklad>();
        }
    
        public int ExponatID { get; set; }
        public string NazvanieExponata { get; set; }
        public string Cena { get; set; }
        public string KolvoLet { get; set; }
        public string GdeNashli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posetiteli> Posetiteli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
    }
}
