//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_Muzey.Baza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuzeyEntities : DbContext
    {

        private static MuzeyEntities _context;
        public MuzeyEntities()
            : base("name=MuzeyEntities")
        {
        }

        public static MuzeyEntities GetContext()
        {
            if (_context == null)
                _context = new MuzeyEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exsponati> Exsponati { get; set; }
        public virtual DbSet<Oxrana> Oxrana { get; set; }
        public virtual DbSet<Posetiteli> Posetiteli { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
