//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_Muzey.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oxrana
    {
        public int OxranaID { get; set; }
        public string NameGlavnogo { get; set; }
        public Nullable<System.DateTime> NachaloRaboti { get; set; }
        public string Staj { get; set; }
        public string Pol { get; set; }
    }
}
