//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_Muzey.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posetiteli
    {
        public int PosetitelID { get; set; }
        public Nullable<int> PokupkaID { get; set; }
        public string Pol { get; set; }
        public string Vosrast { get; set; }
        public string CelPoxoda { get; set; }
    
        public virtual Exsponati Exsponati { get; set; }
    }
}
