//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_Muzey.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int SkladID { get; set; }
        public Nullable<int> ExponatID { get; set; }
        public string NazvanieExponata { get; set; }
        public Nullable<System.DateTime> PrivozDate { get; set; }
        public string MestoNaxojdeniya { get; set; }
        public Nullable<int> OxranaID { get; set; }
        public Nullable<int> SotrudnikiID { get; set; }
    
        public virtual Exsponati Exsponati { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
